<?php

//#######################################################################
// Extension Manager/Repository config file for ext: "jwtools2"
//
// Auto generated by Extension Builder 2016-03-29
//
// Manual updates:
// Only the data in the array - anything else is removed by next write.
// "version" and "dependencies" must not be touched!
//#######################################################################

$EM_CONF[$_EXTKEY] = [
    'title' => 'Walls.io Proxy',
    'description' => 'Cache and Proxy for walls.io, so no Cookie will be set on Client',
    'category' => 'plugin',
    'author' => 'Stefan Froemken',
    'author_email' => 'projects@jweiland.net',
    'author_company' => 'jweiland.net',
    'state' => 'stable',
    'version' => '4.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.14-9.5.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
