
name: tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s lint

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install testing system
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composerValidate

      - name: CGL
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.php }} -t 11 -s cgl

      - name: phpstan
        run: Build/Scripts/runTests.sh -n -p ${{ matrix.php }} -t 11 -s phpstan
